import discord
from discord.ext import commands
import asyncio
import os
import datetime
intents = discord.Intents.default()
#-----SETUP-----#
prefix = '$'

#use the .env feature to hide your token
bet = '1'
token = "MTA0ODU0OTQ1NzU5NzMwODk5OA.Gr_O9r.TcFioOiPrDjHqthCwp0kTRiSyUNVvZtYhK48uM"
#---------------#

bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True,intents=intents)


@bot.event
async def on_ready():
      activity = discord.Game(
            name="OwO",
            large_image = "https://i.pinimg.com/originals/97/6d/5c/976d5c4f4522e5a1ae782516b58518f6.jpg",
            large_text = "Owo AutoFarming ",
            small_image = "https://www.pngitem.com/middle/hxohmTR_24-hour-service-support-24-7-icon-png/",
            small_text = "24/7",)
      await bot.change_presence(status=discord.Status.dnd, activity=activity)
            
print()
print(
    '''THANKS FOR USING THIS SELF BOT IS READY USE $help TO KNOW ALL COMMANDS 

selfbot is ready!
''')


@bot.command(pass_context=True)
async def autoOwO(ctx):
    await ctx.message.delete()
    await ctx.send('💰 Auto OwO Farm Is **Enabled** !')
    global dmcs 
    dmcs = True
    while dmcs:
        async with ctx.typing():
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(8)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(11)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(18)
            await ctx.send('owo cash')
            await asyncio.sleep(12)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(17)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(12)
            await ctx.send('owo cash')
            await asyncio.sleep(15)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(14)
            await ctx.send('owo cash')
    
            await ctx.send(":warning: | **Stage One Completed pls Wait 5mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!**")
            print("Stage One Completed pls Wait 5mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!")
            await asyncio.sleep(300)
            await ctx.send(":warning: | **Restarting AutoOwO Farm**")
            print("Restarting AutoOwO Farm")
            
    
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(8)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(11)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(18)
            await ctx.send('owo cash')
            await asyncio.sleep(12)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(17)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(12)
            await ctx.send('owo cash')
            await asyncio.sleep(15)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(14)
            await ctx.send('owo cash')
            
            await ctx.send(":warning: | **Stage Two Completed pls Wait 10mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!**")
            print("Stage Two Completed pls Wait 10mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!")
            await asyncio.sleep(900)
            await ctx.send(":warning: | **Restarting AutoOwO Farm**")
            print("Restarting AutoOwO Farm")

            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(8)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(11)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(18)
            await ctx.send('owo cash')
            await asyncio.sleep(12)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(17)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(12)
            await ctx.send('owo cash')
            await asyncio.sleep(15)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo flip {bet}')
            await asyncio.sleep(14)
            await ctx.send('owo cash')
            await ctx.send(":warning: | **Stage Three Completed pls Wait 15mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!**")
            print("Stage Three Completed pls Wait 15mins! \n Dont Use Any OwO Or AutoOwO Commands in This Moment Chances To Get Ban!")
            await asyncio.sleep(1200)
            await ctx.send(":warning: | **Restarting AutoOwO Farm**")
            print("Restarting AutoOwO Farm")

@bot.command()
async def help(ctx):
    await ctx.message.delete()
    await ctx.send('***```I: $autoOwO      - for start autoOwO.```***')
    await ctx.send('***```II:$autoBattle   - for for starting autoBattle ```***')
    
async def autoBattle(ctx):
    await ctx.message.delete()
    await ctx.send('💰 Auto OwO Farm Is **Enabled** !')
    global dmcs 
    dmcs = True
    while dmcs:
        async with ctx.typing():
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(8)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(11)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(18)
            await ctx.send('owo cash')
            await asyncio.sleep(12)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(10)
            await ctx.send('owo cash')
            await asyncio.sleep(5)
            await ctx.send('owoh')
            await asyncio.sleep(17)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(12)
            await ctx.send('owo cash')
            await asyncio.sleep(15)
            await ctx.send('owoh')
            await asyncio.sleep(15)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(9)
            await ctx.send('owo cash')
            await asyncio.sleep(13)
            await ctx.send('owoh')
            await asyncio.sleep(14)
            await ctx.send('owo sell all')
            await ctx.send(f'owo battle')
            await asyncio.sleep(14)
            await ctx.send('owo pray')
            await asyncio.sleep(300)
async def on_message(message):
    username = str(message.author).split("#")[0]
    channel = str(message.channel.name)
    user_message = str(message.content)
    print(f'[{message.guild.name}] [{channel}] ({username}): [ {user_message} ]')            
bot.run(token, bot=False)
